### ISSUE TITLE
Extension hangs

### ISSUE THREAD

**Issue by tomrich84** [kaovilai/distill-web-monitor#2]
I've just added Distill to Firefox to give it a go. However, whenever I click on the icon on the menu bar to arrange the settings to monitor a webpage. the pop-out window just hangs, with a 'loading' notification. This does not happen with the extension on Chrome browser.

**Comment by kaovilai** [comment]
I'm not owner or operators of distill. This is only a place for my scripts.

The support team is relatively responsive so go email them.
